services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hex-vite-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_DATABASE_MODE=${VITE_DATABASE_MODE:-memory}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL:-}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY:-}
    restart: unless-stopped
    networks:
      - hex-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Optional: Reverse proxy for SSL termination and load balancing
  nginx-proxy:
    image: nginx:alpine
    container_name: hex-nginx-proxy
    ports:
      - "443:443"
    volumes:
      - ./docker/nginx-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./docker/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - hex-network
    profiles:
      - with-ssl

networks:
  hex-network:
    driver: bridge